name: ETHRegistrarController
description: ens new registrar
networks:
- id: 1
  start_block: 0
  contracts:
  - name: ETHRegistrarController
    address:
    - 0x253553366Da8546fC250F225fe3d25d0C782303b
    abi_file_path: null
    handler: src/EventHandlers.ts
    events:
    - event: NameRegistered(string name, bytes32 indexed label, address indexed owner, uint256 baseCost, uint256 premium, uint256 expires)
      requiredEntities:
      - name: EventsSummary
    - event: NameRenewed(string name, bytes32 indexed label, uint256 cost, uint256 expires)
      requiredEntities:
      - name: EventsSummary
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      requiredEntities:
      - name: EventsSummary
